CREATE TABLE shops (id text PRIMARY KEY, name text NOT NULL, created_at bigint NOT NULL, plan text NOT NULL DEFAULT 'free', plan_until bigint);
CREATE TABLE users (id text PRIMARY KEY, email text NOT NULL UNIQUE, password_hash text NOT NULL, shop_id text NOT NULL REFERENCES shops(id) ON DELETE CASCADE, created_at bigint NOT NULL, role text NOT NULL DEFAULT 'designer');
CREATE TABLE sessions (token text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at bigint NOT NULL, expires_at bigint NOT NULL);
CREATE TABLE shop_profiles (shop_id text PRIMARY KEY REFERENCES shops(id) ON DELETE CASCADE, json text NOT NULL, updated_at bigint NOT NULL);
CREATE TABLE projects (id text PRIMARY KEY, shop_id text NOT NULL REFERENCES shops(id) ON DELETE CASCADE, name text NOT NULL, json text NOT NULL, updated_at bigint NOT NULL);
CREATE INDEX projects_shop ON projects (shop_id, updated_at DESC);
CREATE INDEX sessions_user ON sessions (user_id);
CREATE TABLE invites (token text PRIMARY KEY, shop_id text NOT NULL REFERENCES shops(id) ON DELETE CASCADE, created_by text NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at bigint NOT NULL, expires_at bigint NOT NULL, used_by text REFERENCES users(id) ON DELETE SET NULL, used_at bigint, revoked_at bigint, role text NOT NULL DEFAULT 'designer');
CREATE INDEX invites_shop ON invites (shop_id, created_at DESC);
CREATE TABLE shares (code text PRIMARY KEY, key text NOT NULL, json text NOT NULL, created_at bigint NOT NULL, updated_at bigint NOT NULL, expires_at bigint NOT NULL, shop_id text REFERENCES shops(id) ON DELETE CASCADE);
CREATE INDEX shares_expiry ON shares (expires_at);
CREATE TABLE comments (id text PRIMARY KEY, code text NOT NULL REFERENCES shares(code) ON DELETE CASCADE, target_id text, body text NOT NULL, author text NOT NULL, author_role text NOT NULL CHECK (author_role IN ('client','designer','creator')), reply_to text REFERENCES comments(id) ON DELETE CASCADE, user_id text REFERENCES users(id) ON DELETE SET NULL, created_at bigint NOT NULL);
CREATE INDEX comments_code ON comments (code, created_at);
CREATE TABLE request_limits (bucket text NOT NULL, subject text NOT NULL, window_start bigint NOT NULL, attempts bigint NOT NULL, PRIMARY KEY (bucket,subject,window_start));
CREATE TABLE library_items (user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, id text NOT NULL, json text NOT NULL, updated_at bigint NOT NULL, PRIMARY KEY (user_id,id));
CREATE TABLE shop_catalog_imports (id text PRIMARY KEY, shop_id text NOT NULL REFERENCES shops(id) ON DELETE CASCADE, uploaded_by text NOT NULL REFERENCES users(id) ON DELETE CASCADE, format text NOT NULL, json text NOT NULL, byte_size bigint NOT NULL, rights_confirmed_at bigint NOT NULL, created_at bigint NOT NULL);
CREATE INDEX shop_catalog_imports_shop ON shop_catalog_imports (shop_id, created_at DESC);
CREATE TABLE installation_tasks (id text PRIMARY KEY, shop_id text NOT NULL REFERENCES shops(id) ON DELETE CASCADE, project_id text NOT NULL REFERENCES projects(id) ON DELETE CASCADE, json text NOT NULL, updated_at bigint NOT NULL);
CREATE INDEX installation_tasks_shop ON installation_tasks (shop_id, updated_at DESC);
CREATE TABLE installation_actions (id text PRIMARY KEY, shop_id text NOT NULL REFERENCES shops(id) ON DELETE CASCADE, task_id text NOT NULL REFERENCES installation_tasks(id) ON DELETE CASCADE, request_json text NOT NULL, revision_version bigint NOT NULL, revision_updated_at bigint NOT NULL);
CREATE TABLE installation_events (id text PRIMARY KEY, shop_id text NOT NULL REFERENCES shops(id) ON DELETE CASCADE, task_id text NOT NULL UNIQUE REFERENCES installation_tasks(id) ON DELETE CASCADE, kind text NOT NULL, payload_json text NOT NULL, created_at bigint NOT NULL, processed_at bigint);
CREATE TABLE mobile_measurements (shop_id text NOT NULL REFERENCES shops(id) ON DELETE CASCADE, id text NOT NULL, json text NOT NULL, revision_version bigint NOT NULL, revision_updated_at bigint NOT NULL, PRIMARY KEY (shop_id,id));
CREATE TABLE mobile_measurement_actions (shop_id text NOT NULL REFERENCES shops(id) ON DELETE CASCADE, id text NOT NULL, entity_id text NOT NULL, request_json text NOT NULL, revision_version bigint NOT NULL, revision_updated_at bigint NOT NULL, PRIMARY KEY (shop_id,id));
CREATE TABLE mobile_measurement_photos (shop_id text NOT NULL REFERENCES shops(id) ON DELETE CASCADE, id text NOT NULL, mime text NOT NULL, bytes bytea NOT NULL, sha256 text NOT NULL, created_at bigint NOT NULL, PRIMARY KEY (shop_id,id));
CREATE TABLE approval_revisions (id text PRIMARY KEY, share_code text NOT NULL, share_created_at bigint NOT NULL, shop_id text NOT NULL, version bigint NOT NULL, project_json text NOT NULL, hash text NOT NULL, price_minor bigint NOT NULL, created_at bigint NOT NULL, seal_json text, otp_hash text NOT NULL, attempts bigint NOT NULL DEFAULT 0, preview_png bytea, UNIQUE (share_code,share_created_at,version));
