/**
 * ДЕКОРЛАР КІТАПХАНАСЫ — плитаның түрлері (Egger, Kronospan, Cleaf, SMart,
 * Byspan, Томский ДСП).
 *
 * НЕГЕ КІТАПХАНА ЖӘНЕ ПРОФИЛЬ БӨЛЕК. Цех 500 декордың бәрін САТЫП АЛМАЙДЫ:
 * ол бес-он декормен жұмыс істейді, ал қоймасында да, бағасында да солар
 * тұрады. Сондықтан кітапхана — ТАҢДАУ ҮШІН тізім, ал цехтың профиліне тек
 * өзі қосқаны түседі (`AddMaterial`). Осылайша смета да, раскрой да цехтың
 * нақты материалымен есептеледі.
 *
 * ⚠ ТҮС — ШАМАМЕН. Ол декордың АТЫНАН шығарылған (дуб → сарғыш, бетон →
 * сұр), себебі нағыз реңк жеткізушінің физикалық үлгісінде ғана болады.
 * Түс тек 3D көрінісіне әсер етеді — деталировкаға да, раскройға да, сметаға
 * да ЕШҚАНДАЙ қатысы жоқ. Цех өз материалын қосқанда түсін дәлдей алады.
 *
 * ⚠ АРТИКУЛ — ӨНДІРУШІНІКІ. Бұл — жеткізушінің каталогындағы ашық деректер
 * (Egger H1145, Kronospan K076 …), сондықтан цех қағазымен салыстыра алады.
 * Бағасы мұнда ЖОҚ әрі болмайды да: ол әр цехта басқа (§6).
 */

export type DecorKind = 'chipboard' | 'mdf' | 'hardboard' | 'other'

export type DecorEntry = {
  id: string
  /** Жеткізушінің каталогындағы толық атауы. */
  name: string
  /** Бренд: тізімді сүзу үшін. Белгісізде — бос жол. */
  brand: string
  /** Артикул (H1145, K076…). Кейбір позицияларда болмайды. */
  code: string
  kind: DecorKind
  /** ⚠ ШАМАМЕН, атынан шығарылған. */
  color: string
  /** Текстурасы бар ма — раскройда деталь бұрылмайды. */
  hasGrain: boolean
}

export const DECOR_LIBRARY: DecorEntry[] = [

  { id: 'byspan-812', name: 'Byspan 812 Королевский шёлк', brand: 'Byspan', code: '', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: 'byspan-806', name: 'Byspan 806 Капучино', brand: 'Byspan', code: '', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: 'byspan-612', name: 'Byspan 612 Серый', brand: 'Byspan', code: '', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'byspan-528', name: 'Byspan 528 Сосна Карелия', brand: 'Byspan', code: '', kind: 'chipboard', color: '#c8a578', hasGrain: true },
  { id: 'byspan-402', name: 'Byspan 402 Ноче Милано', brand: 'Byspan', code: '', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: 'byspan-376', name: 'Byspan 376 Дуб Вотан', brand: 'Byspan', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'byspan-354', name: 'Byspan 354 Дуб Марбург', brand: 'Byspan', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'smart-w006', name: 'SMart W006 Wow! · Pampas', brand: 'SMart', code: 'W006', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'smart-w005', name: 'SMart W005 Wow! · Tundra', brand: 'SMart', code: 'W005', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'smart-w003', name: 'SMart W003 Wow! · Patagonia', brand: 'SMart', code: 'W003', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'smart-w002', name: 'SMart W002 Wow! · Savana', brand: 'SMart', code: 'W002', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'smart-u005', name: 'SMart U005 Urban · Iron', brand: 'SMart', code: 'U005', kind: 'chipboard', color: '#2b2d30', hasGrain: false },
  { id: 'smart-u002', name: 'SMart U002 Urban · Concrete', brand: 'SMart', code: 'U002', kind: 'chipboard', color: '#a2a3a1', hasGrain: false },
  { id: 'smart-u001', name: 'SMart U001 Urban · Wall', brand: 'SMart', code: 'U001', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'smart-ol04', name: 'SMart OL04 Olympus · Apollo', brand: 'SMart', code: 'OL04', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'smart-ol02', name: 'SMart OL02 Olympus · Athena', brand: 'SMart', code: 'OL02', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'smart-ol01', name: 'SMart OL01 Olympus · Zeus', brand: 'SMart', code: 'OL01', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'smart-ol00', name: 'SMart OL00 Olympus · Aphrodite', brand: 'SMart', code: 'OL00', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'smart-n005', name: 'SMart N005 Nirvana · Ferro', brand: 'SMart', code: 'N005', kind: 'chipboard', color: '#2b2d30', hasGrain: false },
  { id: 'smart-n004', name: 'SMart N004 Nirvana · Zinco', brand: 'SMart', code: 'N004', kind: 'chipboard', color: '#a2a3a1', hasGrain: false },
  { id: 'smart-n003', name: 'SMart N003 Nirvana · Nichel', brand: 'SMart', code: 'N003', kind: 'chipboard', color: '#a2a3a1', hasGrain: false },
  { id: 'smart-n002', name: 'SMart N002 Nirvana · Mercurio', brand: 'SMart', code: 'N002', kind: 'chipboard', color: '#a2a3a1', hasGrain: false },
  { id: 'smart-n001', name: 'SMart N001 Nirvana · Platino', brand: 'SMart', code: 'N001', kind: 'chipboard', color: '#a2a3a1', hasGrain: false },
  { id: 'smart-s000', name: 'SMart S000 Club · Silverdust', brand: 'SMart', code: 'S000', kind: 'chipboard', color: '#a2a3a1', hasGrain: false },
  { id: 'smart-c007', name: 'SMart C007 Club · Ski', brand: 'SMart', code: 'C007', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'smart-c005', name: 'SMart C005 Club · Cricket', brand: 'SMart', code: 'C005', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'smart-c003', name: 'SMart C003 Club · Polo', brand: 'SMart', code: 'C003', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'smart-3096-club-bianco', name: 'SMart 3096 Club · Bianco', brand: 'SMart', code: '', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'cleaf-s017', name: 'Cleaf S017 Yosemite · Sierra', brand: 'Cleaf', code: 'S017', kind: 'chipboard', color: '#b8b4ac', hasGrain: true },
  { id: 'cleaf-s013', name: 'Cleaf S013 Yosemite · Old Jack', brand: 'Cleaf', code: 'S013', kind: 'chipboard', color: '#b8b4ac', hasGrain: true },
  { id: 'cleaf-s012', name: 'Cleaf S012 Yosemite · Burned', brand: 'Cleaf', code: 'S012', kind: 'chipboard', color: '#b8b4ac', hasGrain: true },
  { id: 'cleaf-s011', name: 'Cleaf S011 Yosemite · Milk Shake', brand: 'Cleaf', code: 'S011', kind: 'chipboard', color: '#f2f0ec', hasGrain: true },
  { id: 'cleaf-lm12', name: 'Cleaf LM12 Tranche', brand: 'Cleaf', code: 'LM12', kind: 'chipboard', color: '#b8b4ac', hasGrain: true },
  { id: 'cleaf-lm09', name: 'Cleaf LM09 Tranche', brand: 'Cleaf', code: 'LM09', kind: 'chipboard', color: '#b8b4ac', hasGrain: true },
  { id: 'cleaf-lm08', name: 'Cleaf LM08 Tranche', brand: 'Cleaf', code: 'LM08', kind: 'chipboard', color: '#b8b4ac', hasGrain: true },
  { id: 'cleaf-s143', name: 'Cleaf S143 Tivoli', brand: 'Cleaf', code: 'S143', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-fa96', name: 'Cleaf FA96 Spigato', brand: 'Cleaf', code: 'FA96', kind: 'chipboard', color: '#b8b4ac', hasGrain: true },
  { id: 'cleaf-fa90', name: 'Cleaf FA90 Spigato', brand: 'Cleaf', code: 'FA90', kind: 'chipboard', color: '#b8b4ac', hasGrain: true },
  { id: 'cleaf-so75', name: 'Cleaf SO75 Sherwood', brand: 'Cleaf', code: 'SO75', kind: 'chipboard', color: '#b8b4ac', hasGrain: true },
  { id: 'cleaf-so72', name: 'Cleaf SO72 Sherwood', brand: 'Cleaf', code: 'SO72', kind: 'chipboard', color: '#b8b4ac', hasGrain: true },
  { id: 'cleaf-so71', name: 'Cleaf SO71 Sherwood', brand: 'Cleaf', code: 'SO71', kind: 'chipboard', color: '#b8b4ac', hasGrain: true },
  { id: 'cleaf-ln66', name: 'Cleaf LN66 Sherwood', brand: 'Cleaf', code: 'LN66', kind: 'chipboard', color: '#b8b4ac', hasGrain: true },
  { id: 'cleaf-fa68', name: 'Cleaf FA68 Sherwood', brand: 'Cleaf', code: 'FA68', kind: 'chipboard', color: '#b8b4ac', hasGrain: true },
  { id: 'cleaf-fa33', name: 'Cleaf FA33 Scacco matto', brand: 'Cleaf', code: 'FA33', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-lr29', name: 'Cleaf LR29 Sable', brand: 'Cleaf', code: 'LR29', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-ua08', name: 'Cleaf UA08 Primofiore', brand: 'Cleaf', code: 'UA08', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-fb12', name: 'Cleaf FB12 Primofiore', brand: 'Cleaf', code: 'FB12', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-fa68-2', name: 'Cleaf FA68 Penelope', brand: 'Cleaf', code: 'FA68', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-fa48', name: 'Cleaf FA48 Penelope', brand: 'Cleaf', code: 'FA48', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-fa47', name: 'Cleaf FA47 Penelope', brand: 'Cleaf', code: 'FA47', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-fa44', name: 'Cleaf FA44 Penelope', brand: 'Cleaf', code: 'FA44', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-fa42', name: 'Cleaf FA42 Penelope', brand: 'Cleaf', code: 'FA42', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-s128', name: 'Cleaf S128 Pembroke', brand: 'Cleaf', code: 'S128', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-s119', name: 'Cleaf S119 Pembroke', brand: 'Cleaf', code: 'S119', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-ln02', name: 'Cleaf LN02 Nadir', brand: 'Cleaf', code: 'LN02', kind: 'chipboard', color: '#b8b4ac', hasGrain: true },
  { id: 'cleaf-ln01', name: 'Cleaf LN01 Nadir', brand: 'Cleaf', code: 'LN01', kind: 'chipboard', color: '#b8b4ac', hasGrain: true },
  { id: 'cleaf-fa08', name: 'Cleaf FA08 Nadir', brand: 'Cleaf', code: 'FA08', kind: 'chipboard', color: '#b8b4ac', hasGrain: true },
  { id: 'cleaf-ua01', name: 'Cleaf UA01 Millennium', brand: 'Cleaf', code: 'UA01', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-u129-1', name: 'Cleaf U129(1) Millennium', brand: 'Cleaf', code: 'U129(1)', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-so83', name: 'Cleaf SO83 Millennium', brand: 'Cleaf', code: 'SO83', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-bo73', name: 'Cleaf BO73 Millennium', brand: 'Cleaf', code: 'BO73', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-lm63', name: 'Cleaf LM63 Matrix', brand: 'Cleaf', code: 'LM63', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-lm62', name: 'Cleaf LM62 Matrix', brand: 'Cleaf', code: 'LM62', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-fb02', name: 'Cleaf FB02 Maloja', brand: 'Cleaf', code: 'FB02', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-so65', name: 'Cleaf SO65 Engadina', brand: 'Cleaf', code: 'SO65', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-so61', name: 'Cleaf SO61 Engadina', brand: 'Cleaf', code: 'SO61', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-so60', name: 'Cleaf SO60 Engadina', brand: 'Cleaf', code: 'SO60', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-so28', name: 'Cleaf SO28 Azimut', brand: 'Cleaf', code: 'SO28', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-so27', name: 'Cleaf SO27 Azimut', brand: 'Cleaf', code: 'SO27', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-so25', name: 'Cleaf SO25 Azimut', brand: 'Cleaf', code: 'SO25', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-so24', name: 'Cleaf SO24 Azimut', brand: 'Cleaf', code: 'SO24', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-bo11', name: 'Cleaf BO11 Azimut', brand: 'Cleaf', code: 'BO11', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-ua91', name: 'Cleaf UA91 Ares', brand: 'Cleaf', code: 'UA91', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-fb50', name: 'Cleaf FB50 Ares', brand: 'Cleaf', code: 'FB50', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-fb48', name: 'Cleaf FB48 Ares', brand: 'Cleaf', code: 'FB48', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf-fb11', name: 'Cleaf FB11 Ares', brand: 'Cleaf', code: 'FB11', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k9561', name: 'Kronospan K9561 Зеленый Оксид', brand: 'Kronospan', code: 'K9561', kind: 'chipboard', color: '#4d6350', hasGrain: false },
  { id: 'kronospan-k9551', name: 'Kronospan K9551 Красный Оксид', brand: 'Kronospan', code: 'K9551', kind: 'chipboard', color: '#8d3a32', hasGrain: false },
  { id: 'kronospan-k8984', name: 'Kronospan K8984 Морской Синий', brand: 'Kronospan', code: 'K8984', kind: 'chipboard', color: '#3a5578', hasGrain: false },
  { id: 'kronospan-k8685', name: 'Kronospan K8685 Белый снег', brand: 'Kronospan', code: 'K8685', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'kronospan-k8681', name: 'Kronospan K8681 Белый Бриллиант', brand: 'Kronospan', code: 'K8681', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'kronospan-k8533', name: 'Kronospan K8533 Макиато', brand: 'Kronospan', code: 'K8533', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: 'kronospan-k8100', name: 'Kronospan K8100 Белый Жемчуг', brand: 'Kronospan', code: 'K8100', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'kronospan-k7190', name: 'Kronospan K7190 Зеленая Мамба', brand: 'Kronospan', code: 'K7190', kind: 'chipboard', color: '#4d6350', hasGrain: false },
  { id: 'kronospan-k7181', name: 'Kronospan K7181 Темный шоколад', brand: 'Kronospan', code: 'K7181', kind: 'chipboard', color: '#6b4c3a', hasGrain: false },
  { id: 'kronospan-k7166', name: 'Kronospan K7166 Латте', brand: 'Kronospan', code: 'K7166', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: 'kronospan-k7113', name: 'Kronospan K7113 Красный Чили', brand: 'Kronospan', code: 'K7113', kind: 'chipboard', color: '#8d3a32', hasGrain: false },
  { id: 'kronospan-k7063', name: 'Kronospan K7063 Пастельный Зеленый', brand: 'Kronospan', code: 'K7063', kind: 'chipboard', color: '#c8a578', hasGrain: true },
  { id: 'kronospan-k7045', name: 'Kronospan K7045 Сатин', brand: 'Kronospan', code: 'K7045', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'kronospan-k7031', name: 'Kronospan K7031 Кремовый', brand: 'Kronospan', code: 'K7031', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: 'kronospan-k697', name: 'Kronospan K697 Cocoa Primavera Oak', brand: 'Kronospan', code: 'K697', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k696', name: 'Kronospan K696 Umber Primavera Oak', brand: 'Kronospan', code: 'K696', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k695', name: 'Kronospan K695 Straw Primavera Oak', brand: 'Kronospan', code: 'K695', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k694', name: 'Kronospan K694 Silk Primavera Oak', brand: 'Kronospan', code: 'K694', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k693', name: 'Kronospan K693 Bronze Granada', brand: 'Kronospan', code: 'K693', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k692', name: 'Kronospan K692 Cloud Granada', brand: 'Kronospan', code: 'K692', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k691', name: 'Kronospan K691 Almond Granada', brand: 'Kronospan', code: 'K691', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k687', name: 'Kronospan K687 Dark Forest', brand: 'Kronospan', code: 'K687', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k686', name: 'Kronospan K686 Powder Pink', brand: 'Kronospan', code: 'K686', kind: 'chipboard', color: '#c9a5a0', hasGrain: false },
  { id: 'kronospan-k685', name: 'Kronospan K685 Steel Blue', brand: 'Kronospan', code: 'K685', kind: 'chipboard', color: '#a2a3a1', hasGrain: false },
  { id: 'kronospan-k684', name: 'Kronospan K684 Black Truffle', brand: 'Kronospan', code: 'K684', kind: 'chipboard', color: '#2b2d30', hasGrain: false },
  { id: 'kronospan-k683', name: 'Kronospan K683 Cajun', brand: 'Kronospan', code: 'K683', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k682', name: 'Kronospan K682 Alpaca', brand: 'Kronospan', code: 'K682', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k681', name: 'Kronospan K681 Macadamia', brand: 'Kronospan', code: 'K681', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k680', name: 'Kronospan K680 Stone Beige', brand: 'Kronospan', code: 'K680', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'kronospan-k6299', name: 'Kronospan K6299 Кобальт Серый', brand: 'Kronospan', code: 'K6299', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'kronospan-k5994', name: 'Kronospan K5994 Альби голубой', brand: 'Kronospan', code: 'K5994', kind: 'chipboard', color: '#3a5578', hasGrain: false },
  { id: 'kronospan-k5982', name: 'Kronospan K5982 Мидия', brand: 'Kronospan', code: 'K5982', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k5981', name: 'Kronospan K5981 Кашемир', brand: 'Kronospan', code: 'K5981', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k564', name: 'Kronospan K564 Миндаль', brand: 'Kronospan', code: 'K564', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k554', name: 'Kronospan K554 Дуб Гудзон шоколадный', brand: 'Kronospan', code: 'K554', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k548', name: 'Kronospan K548 Ясень Кала дымчатый', brand: 'Kronospan', code: 'K548', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'kronospan-k547', name: 'Kronospan K547 Орех Франклин табачный', brand: 'Kronospan', code: 'K547', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: 'kronospan-k546', name: 'Kronospan K546 Орех Франклин карамель', brand: 'Kronospan', code: 'K546', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: 'kronospan-k545', name: 'Kronospan K545 Дуб Сильверджек винтаж', brand: 'Kronospan', code: 'K545', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k544', name: 'Kronospan K544 Дуб Сильверджек ореховый', brand: 'Kronospan', code: 'K544', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k543', name: 'Kronospan K543 Дуб Барбера песочный', brand: 'Kronospan', code: 'K543', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k542', name: 'Kronospan K542 Тессея мокко', brand: 'Kronospan', code: 'K542', kind: 'chipboard', color: '#6b4c3a', hasGrain: false },
  { id: 'kronospan-k541', name: 'Kronospan K541 Тессея серо-бежевый', brand: 'Kronospan', code: 'K541', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'kronospan-k540', name: 'Kronospan K540 Альбус серый', brand: 'Kronospan', code: 'K540', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'kronospan-k539', name: 'Kronospan K539 Ароза темно-серый', brand: 'Kronospan', code: 'K539', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'kronospan-k538', name: 'Kronospan K538 Ароза светло-серый', brand: 'Kronospan', code: 'K538', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'kronospan-k537', name: 'Kronospan K537 Дуб Барокко ристретто', brand: 'Kronospan', code: 'K537', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k536', name: 'Kronospan K536 Дуб Барокко янтарный', brand: 'Kronospan', code: 'K536', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k535', name: 'Kronospan K535 Дуб Барокко золотой', brand: 'Kronospan', code: 'K535', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k534', name: 'Kronospan K534 Каштан Арвадонна угольный', brand: 'Kronospan', code: 'K534', kind: 'chipboard', color: '#6b4c3a', hasGrain: false },
  { id: 'kronospan-k533', name: 'Kronospan K533 Каштан Арвадонна серо-коричневый', brand: 'Kronospan', code: 'K533', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'kronospan-k532', name: 'Kronospan K532 Каштан Арвадонна пламенный', brand: 'Kronospan', code: 'K532', kind: 'chipboard', color: '#6b4c3a', hasGrain: false },
  { id: 'kronospan-k531', name: 'Kronospan K531 Каштан Арвадонна окаменелый', brand: 'Kronospan', code: 'K531', kind: 'chipboard', color: '#6b4c3a', hasGrain: false },
  { id: 'kronospan-k530', name: 'Kronospan K530 Дуб Гудзон амаретто', brand: 'Kronospan', code: 'K530', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k529', name: 'Kronospan K529 Дуб Гудзон золотой', brand: 'Kronospan', code: 'K529', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k528', name: 'Kronospan K528 Дуб Гудзон кашемир', brand: 'Kronospan', code: 'K528', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k527', name: 'Kronospan K527 Дуб Гудзон бискотти', brand: 'Kronospan', code: 'K527', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k526', name: 'Kronospan K526 Ясень Серфсайд темный', brand: 'Kronospan', code: 'K526', kind: 'chipboard', color: '#9a9a97', hasGrain: true },
  { id: 'kronospan-k525', name: 'Kronospan K525 Ясень Серфсайд светлый', brand: 'Kronospan', code: 'K525', kind: 'chipboard', color: '#9a9a97', hasGrain: true },
  { id: 'kronospan-k524', name: 'Kronospan K524 Ясень Серфсайд натуральный', brand: 'Kronospan', code: 'K524', kind: 'chipboard', color: '#9a9a97', hasGrain: true },
  { id: 'kronospan-k523', name: 'Kronospan K523 Диск платиновый', brand: 'Kronospan', code: 'K523', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'kronospan-k522', name: 'Kronospan K522 Флэш алюминий', brand: 'Kronospan', code: 'K522', kind: 'chipboard', color: '#a2a3a1', hasGrain: false },
  { id: 'kronospan-k521', name: 'Kronospan K521 Дымчато-зеленый', brand: 'Kronospan', code: 'K521', kind: 'chipboard', color: '#4d6350', hasGrain: false },
  { id: 'kronospan-k520', name: 'Kronospan K520 Темный изумруд', brand: 'Kronospan', code: 'K520', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k519', name: 'Kronospan K519 Мышиный серый', brand: 'Kronospan', code: 'K519', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'kronospan-k518', name: 'Kronospan K518 Прибрежный голубой', brand: 'Kronospan', code: 'K518', kind: 'chipboard', color: '#3a5578', hasGrain: false },
  { id: 'kronospan-k517', name: 'Kronospan K517 Лазурно-голубой', brand: 'Kronospan', code: 'K517', kind: 'chipboard', color: '#3a5578', hasGrain: false },
  { id: 'kronospan-k516', name: 'Kronospan K516 Тоффи', brand: 'Kronospan', code: 'K516', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k515', name: 'Kronospan K515 Красный пряный', brand: 'Kronospan', code: 'K515', kind: 'chipboard', color: '#8d3a32', hasGrain: false },
  { id: 'kronospan-k514', name: 'Kronospan K514 Дип Сахара (Безмолвная пустыня)', brand: 'Kronospan', code: 'K514', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k513', name: 'Kronospan K513 Маршмеллоу', brand: 'Kronospan', code: 'K513', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k512', name: 'Kronospan K512 Розовый натуральный', brand: 'Kronospan', code: 'K512', kind: 'chipboard', color: '#c9a5a0', hasGrain: false },
  { id: 'kronospan-k366', name: 'Kronospan K366 Дуб Эвок Окаменелый', brand: 'Kronospan', code: 'K366', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k365', name: 'Kronospan K365 Дуб Эвок Прибрежный', brand: 'Kronospan', code: 'K365', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k361', name: 'Kronospan K361 Дуб Харбор Золотой', brand: 'Kronospan', code: 'K361', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k360', name: 'Kronospan K360 Дуб Харбор Винтажный', brand: 'Kronospan', code: 'K360', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k359', name: 'Kronospan K359 Дуб Кастелло Бренди', brand: 'Kronospan', code: 'K359', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k358', name: 'Kronospan K358 Дуб Кастелло Медовый', brand: 'Kronospan', code: 'K358', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k357', name: 'Kronospan K357 Дуб Кастелло Серый', brand: 'Kronospan', code: 'K357', kind: 'chipboard', color: '#9a9a97', hasGrain: true },
  { id: 'kronospan-k356', name: 'Kronospan K356 Дуб Гранж Песочный', brand: 'Kronospan', code: 'K356', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k355', name: 'Kronospan K355 Дуб Гранж Платиновый', brand: 'Kronospan', code: 'K355', kind: 'chipboard', color: '#f2f0ec', hasGrain: true },
  { id: 'kronospan-k354', name: 'Kronospan K354 Дуб Гранж Колониальный', brand: 'Kronospan', code: 'K354', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k353', name: 'Kronospan K353 Угольный Kамень', brand: 'Kronospan', code: 'K353', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k352', name: 'Kronospan K352 Железный Kамень', brand: 'Kronospan', code: 'K352', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k351', name: 'Kronospan K351 Ржавый Kамень', brand: 'Kronospan', code: 'K351', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k350', name: 'Kronospan K350 Бетонный Kамень', brand: 'Kronospan', code: 'K350', kind: 'chipboard', color: '#a2a3a1', hasGrain: false },
  { id: 'kronospan-k349', name: 'Kronospan K349 Шелковый Kамень', brand: 'Kronospan', code: 'K349', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: 'kronospan-k301', name: 'Kronospan K301 Капучино', brand: 'Kronospan', code: 'K301', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: 'kronospan-k2739', name: 'Kronospan K2739 Cannolo Cremona Oak', brand: 'Kronospan', code: 'K2739', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k2738', name: 'Kronospan K2738 Torro Cremona Oak', brand: 'Kronospan', code: 'K2738', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k2737', name: 'Kronospan K2737 Cotta Cremona Oak', brand: 'Kronospan', code: 'K2737', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k197', name: 'Kronospan K197 Шиншилла Серая', brand: 'Kronospan', code: 'K197', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'kronospan-k191', name: 'Kronospan K191 Холодный Серый', brand: 'Kronospan', code: 'K191', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'kronospan-k190', name: 'Kronospan K190 Черный', brand: 'Kronospan', code: 'K190', kind: 'chipboard', color: '#2b2d30', hasGrain: false },
  { id: 'kronospan-k171', name: 'Kronospan K171 Серый Шифер', brand: 'Kronospan', code: 'K171', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'kronospan-k1700', name: 'Kronospan K1700 Стальной Серый', brand: 'Kronospan', code: 'K1700', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'kronospan-k166', name: 'Kronospan K166 Базальт', brand: 'Kronospan', code: 'K166', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k164', name: 'Kronospan K164 Антрацит', brand: 'Kronospan', code: 'K164', kind: 'chipboard', color: '#2b2d30', hasGrain: false },
  { id: 'kronospan-k162', name: 'Kronospan K162 Серый Графит', brand: 'Kronospan', code: 'K162', kind: 'chipboard', color: '#2b2d30', hasGrain: false },
  { id: 'kronospan-k134', name: 'Kronospan K134 Солнечный Свет', brand: 'Kronospan', code: 'K134', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k132', name: 'Kronospan K132 Оранжевый', brand: 'Kronospan', code: 'K132', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k125', name: 'Kronospan K125 Королевский Синий', brand: 'Kronospan', code: 'K125', kind: 'chipboard', color: '#3a5578', hasGrain: false },
  { id: 'kronospan-k112', name: 'Kronospan K112 Серый Камень', brand: 'Kronospan', code: 'K112', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'kronospan-k110', name: 'Kronospan K110 Белый', brand: 'Kronospan', code: 'K110', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'kronospan-k107', name: 'Kronospan K107 Дуб Эндгрейн Элегантный', brand: 'Kronospan', code: 'K107', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k105', name: 'Kronospan K105 Дуб Эндгрейн Необработанный', brand: 'Kronospan', code: 'K105', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k101', name: 'Kronospan K101 Белый Фасадный', brand: 'Kronospan', code: 'K101', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'kronospan-k098', name: 'Kronospan K098 Керамический Красный', brand: 'Kronospan', code: 'K098', kind: 'chipboard', color: '#8d3a32', hasGrain: false },
  { id: 'kronospan-k097', name: 'Kronospan K097 Сумеречный Голубой', brand: 'Kronospan', code: 'K097', kind: 'chipboard', color: '#3a5578', hasGrain: false },
  { id: 'kronospan-k096', name: 'Kronospan K096 Глиняный Серый', brand: 'Kronospan', code: 'K096', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'kronospan-k090', name: 'Kronospan K090 Дуб Экспресив Бронзовый', brand: 'Kronospan', code: 'K090', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k089', name: 'Kronospan K089 Скандинавское Дерево Серое', brand: 'Kronospan', code: 'K089', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'kronospan-k088', name: 'Kronospan K088 Скандинавское Дерево Белое', brand: 'Kronospan', code: 'K088', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'kronospan-k087', name: 'Kronospan K087 Гикори Рокфорд Темный', brand: 'Kronospan', code: 'K087', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k086', name: 'Kronospan K086 Гикори Рокфорд Натуральный', brand: 'Kronospan', code: 'K086', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k085', name: 'Kronospan K085 Гикори Рокфорд Светлый', brand: 'Kronospan', code: 'K085', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k084', name: 'Kronospan K084 Артвуд Темный', brand: 'Kronospan', code: 'K084', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k083', name: 'Kronospan K083 Артвуд Светлый', brand: 'Kronospan', code: 'K083', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-k082', name: 'Kronospan K082 Дуб Бурбон', brand: 'Kronospan', code: 'K082', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k081', name: 'Kronospan K081 Дуб Приморский Сатиновый', brand: 'Kronospan', code: 'K081', kind: 'chipboard', color: '#9a9a97', hasGrain: true },
  { id: 'kronospan-k080', name: 'Kronospan K080 Дуб Приморский Белый', brand: 'Kronospan', code: 'K080', kind: 'chipboard', color: '#f2f0ec', hasGrain: true },
  { id: 'kronospan-k079', name: 'Kronospan K079 Дуб Клабхаус Серый', brand: 'Kronospan', code: 'K079', kind: 'chipboard', color: '#9a9a97', hasGrain: true },
  { id: 'kronospan-k078', name: 'Kronospan K078 Вишня Риверсайд Темная', brand: 'Kronospan', code: 'K078', kind: 'chipboard', color: '#8d3a32', hasGrain: true },
  { id: 'kronospan-k076', name: 'Kronospan K076 Дуб Экспресив Песочный', brand: 'Kronospan', code: 'K076', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k022', name: 'Kronospan K022 Блэквуд Сатиновый', brand: 'Kronospan', code: 'K022', kind: 'chipboard', color: '#2b2d30', hasGrain: true },
  { id: 'kronospan-k021', name: 'Kronospan K021 Блэквуд Ячменный', brand: 'Kronospan', code: 'K021', kind: 'chipboard', color: '#2b2d30', hasGrain: true },
  { id: 'kronospan-k020', name: 'Kronospan K020 Орех Селект Каминный', brand: 'Kronospan', code: 'K020', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: 'kronospan-k019', name: 'Kronospan K019 Вяз Либерти Серебряный', brand: 'Kronospan', code: 'K019', kind: 'chipboard', color: '#9a9a97', hasGrain: true },
  { id: 'kronospan-k018', name: 'Kronospan K018 Вяз Либерти Дымчатый', brand: 'Kronospan', code: 'K018', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'kronospan-k017', name: 'Kronospan K017 Вяз Либерти Светлый', brand: 'Kronospan', code: 'K017', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'kronospan-k016', name: 'Kronospan K016 Морское Дерево Карбон', brand: 'Kronospan', code: 'K016', kind: 'chipboard', color: '#3a5578', hasGrain: false },
  { id: 'kronospan-k015', name: 'Kronospan K015 Морское Дерево Винтаж', brand: 'Kronospan', code: 'K015', kind: 'chipboard', color: '#3a5578', hasGrain: false },
  { id: 'kronospan-k013', name: 'Kronospan K013 Бук Артизан Песочный', brand: 'Kronospan', code: 'K013', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'kronospan-k012', name: 'Kronospan K012 Бук Артизан Перламутровый', brand: 'Kronospan', code: 'K012', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'kronospan-k010', name: 'Kronospan K010 Сосна Лофт Белая', brand: 'Kronospan', code: 'K010', kind: 'chipboard', color: '#f2f0ec', hasGrain: true },
  { id: 'kronospan-k009', name: 'Kronospan K009 Орех Селект Темный', brand: 'Kronospan', code: 'K009', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: 'kronospan-k008', name: 'Kronospan K008 Орех Селект Светлый', brand: 'Kronospan', code: 'K008', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: 'kronospan-k007', name: 'Kronospan K007 Дуб Урбан Кофейный', brand: 'Kronospan', code: 'K007', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k006', name: 'Kronospan K006 Дуб Урбан Янтарный', brand: 'Kronospan', code: 'K006', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k005', name: 'Kronospan K005 Дуб Урбан Ойстер', brand: 'Kronospan', code: 'K005', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k004', name: 'Kronospan K004 Дуб Крафт Табачный', brand: 'Kronospan', code: 'K004', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k003', name: 'Kronospan K003 Дуб Крафт Золотой', brand: 'Kronospan', code: 'K003', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-k002', name: 'Kronospan K002 Дуб Крафт Серый', brand: 'Kronospan', code: 'K002', kind: 'chipboard', color: '#9a9a97', hasGrain: true },
  { id: 'kronospan-k001', name: 'Kronospan K001 Дуб Крафт Белый', brand: 'Kronospan', code: 'K001', kind: 'chipboard', color: '#f2f0ec', hasGrain: true },
  { id: 'kronospan-9763', name: 'Kronospan 9763 Венге Луизиана', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#3b2f2a', hasGrain: true },
  { id: 'kronospan-9614', name: 'Kronospan 9614 Орех Лион Светлый', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: 'kronospan-8995', name: 'Kronospan 8995 Коко Бола', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-8953', name: 'Kronospan 8953 Орех Тьеполо', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: 'kronospan-8921', name: 'Kronospan 8921 Дуб Феррара', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-8548', name: 'Kronospan 8548 Файнлайн Мокка', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-8431', name: 'Kronospan 8431 Дуб Нагано', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-7648', name: 'Kronospan 7648 Венге Винтаж', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#3b2f2a', hasGrain: true },
  { id: 'kronospan-5529', name: 'Kronospan 5529 Орегон', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan-5527', name: 'Kronospan 5527 Дуб Каменный', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-5501', name: 'Kronospan 5501 Дуб Славония', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-5500', name: 'Kronospan 5500 Вяз Натуральный Благородный', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'kronospan-5194', name: 'Kronospan 5194 Дуб Винтаж Оксид', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-4299', name: 'Kronospan 4299 Ателье Темное', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#c8a578', hasGrain: true },
  { id: 'kronospan-4298', name: 'Kronospan 4298 Ателье Светлое', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#c8a578', hasGrain: true },
  { id: 'kronospan-3025', name: 'Kronospan 3025 Дуб Сонома Светлый', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-1912', name: 'Kronospan 1912 Ольха', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'kronospan-1715', name: 'Kronospan 1715 Береза', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'kronospan-0881', name: 'Kronospan 0881 Алюминий', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#a2a3a1', hasGrain: false },
  { id: 'kronospan-0854', name: 'Kronospan 0854 Венге', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#3b2f2a', hasGrain: true },
  { id: 'kronospan-0740', name: 'Kronospan 0740 Дуб Горный', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'kronospan-0729', name: 'Kronospan 0729 Орех', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: 'kronospan-0540', name: 'Kronospan 0540 Серый Манхеттен', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'kronospan-0522', name: 'Kronospan 0522 Бежевый', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: 'kronospan-0515', name: 'Kronospan 0515 Песочный', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: 'kronospan-0514', name: 'Kronospan 0514 Слоновая Кость', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: 'kronospan-0381', name: 'Kronospan 0381 Бук классический', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'kronospan-0375', name: 'Kronospan 0375 Клен', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'kronospan-0344', name: 'Kronospan 0344 Вишня', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#8d3a32', hasGrain: true },
  { id: 'kronospan-0244', name: 'Kronospan 0244 Бензин', brand: 'Kronospan', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'egger-w980', name: 'Egger W980 ST7 Белый платиновый', brand: 'Egger', code: 'W980', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'egger-w980-2', name: 'Egger W980 ST7 Платиновый белый', brand: 'Egger', code: 'W980', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'egger-w980-3', name: 'Egger W980 SM Белый платиновый', brand: 'Egger', code: 'W980', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'egger-w960', name: 'Egger W960 ST7 Белый классический', brand: 'Egger', code: 'W960', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'egger-w960-2', name: 'Egger W960 SM Белый классический', brand: 'Egger', code: 'W960', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'egger-w1200', name: 'Egger W1200 ST9 Фарфор белый', brand: 'Egger', code: 'W1200', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'egger-w1100', name: 'Egger W1100 ST9 Белый Альпийский', brand: 'Egger', code: 'W1100', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'egger-w1000', name: 'Egger W1000 ST9 Белый Премиум', brand: 'Egger', code: 'W1000', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'egger-w1000-2', name: 'Egger W1000 ST38 Белый Премиум', brand: 'Egger', code: 'W1000', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'egger-w1000-3', name: 'Egger W1000 ST19 Белый премиум', brand: 'Egger', code: 'W1000', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'egger-u999', name: 'Egger U999 ST7 Чёрный', brand: 'Egger', code: 'U999', kind: 'chipboard', color: '#2b2d30', hasGrain: false },
  { id: 'egger-u999-2', name: 'Egger U999 ST20 Чёрный', brand: 'Egger', code: 'U999', kind: 'chipboard', color: '#2b2d30', hasGrain: false },
  { id: 'egger-u999-3', name: 'Egger U999 ST19 Чёрный', brand: 'Egger', code: 'U999', kind: 'chipboard', color: '#2b2d30', hasGrain: false },
  { id: 'egger-u998', name: 'Egger U998 ST38 Лес чёрный', brand: 'Egger', code: 'U998', kind: 'chipboard', color: '#2b2d30', hasGrain: false },
  { id: 'egger-u968', name: 'Egger U968 ST9 Серый уголь', brand: 'Egger', code: 'U968', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-u963', name: 'Egger U963 ST9 Диамант серый', brand: 'Egger', code: 'U963', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-u961', name: 'Egger U961 ST7 Чёрный графит', brand: 'Egger', code: 'U961', kind: 'chipboard', color: '#2b2d30', hasGrain: false },
  { id: 'egger-u960', name: 'Egger U960 ST9 Оникс серый', brand: 'Egger', code: 'U960', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-u899', name: 'Egger U899 ST9 Нежный чёрный', brand: 'Egger', code: 'U899', kind: 'chipboard', color: '#2b2d30', hasGrain: false },
  { id: 'egger-u830', name: 'Egger U830 ST9 Карамель нюд', brand: 'Egger', code: 'U830', kind: 'chipboard', color: '#c8a578', hasGrain: true },
  { id: 'egger-u818', name: 'Egger U818 ST9 Тёмно-коричневый', brand: 'Egger', code: 'U818', kind: 'chipboard', color: '#6b4c3a', hasGrain: false },
  { id: 'egger-u788', name: 'Egger U788 ST9 Арктика серый', brand: 'Egger', code: 'U788', kind: 'chipboard', color: '#9a9a97', hasGrain: true },
  { id: 'egger-u780', name: 'Egger U780 ST9 Серый монументальный', brand: 'Egger', code: 'U780', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-u775', name: 'Egger U775 ST9 Бело-серый', brand: 'Egger', code: 'U775', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'egger-u767', name: 'Egger U767 ST9 Кубанит серый', brand: 'Egger', code: 'U767', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-u763', name: 'Egger U763 ST9 Серый перламутровый', brand: 'Egger', code: 'U763', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-u750', name: 'Egger U750 ST9 Ярко-серый', brand: 'Egger', code: 'U750', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-u748', name: 'Egger U748 ST9 Трюфель коричневый', brand: 'Egger', code: 'U748', kind: 'chipboard', color: '#c8a578', hasGrain: true },
  { id: 'egger-u741', name: 'Egger U741 ST9 Лава серая', brand: 'Egger', code: 'U741', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-u732', name: 'Egger U732 ST9 Серый асфальт', brand: 'Egger', code: 'U732', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-u727', name: 'Egger U727 ST9 Серый камень', brand: 'Egger', code: 'U727', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-u708', name: 'Egger U708 ST9 Светло-серый', brand: 'Egger', code: 'U708', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-u707', name: 'Egger U707 ST9 Шёлк серый', brand: 'Egger', code: 'U707', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-u705', name: 'Egger U705 ST9 Ангора серая', brand: 'Egger', code: 'U705', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-u702', name: 'Egger U702 ST9 Кашемир серый', brand: 'Egger', code: 'U702', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-u699', name: 'Egger U699 ST9 Зелёный еловый', brand: 'Egger', code: 'U699', kind: 'chipboard', color: '#4d6350', hasGrain: false },
  { id: 'egger-u665', name: 'Egger U665 ST9 Зелёный камень', brand: 'Egger', code: 'U665', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-u638', name: 'Egger U638 ST9 Зелёный шалфей', brand: 'Egger', code: 'U638', kind: 'chipboard', color: '#4d6350', hasGrain: false },
  { id: 'egger-u636', name: 'Egger U636 ST9 Фьёрд зелёный', brand: 'Egger', code: 'U636', kind: 'chipboard', color: '#4d6350', hasGrain: false },
  { id: 'egger-u630', name: 'Egger U630 ST9 Зелёный лайм', brand: 'Egger', code: 'U630', kind: 'chipboard', color: '#4d6350', hasGrain: false },
  { id: 'egger-u606', name: 'Egger U606 ST9 Зелёный лес', brand: 'Egger', code: 'U606', kind: 'chipboard', color: '#4d6350', hasGrain: false },
  { id: 'egger-u604', name: 'Egger U604 ST9 Зелёный эвкалипт', brand: 'Egger', code: 'U604', kind: 'chipboard', color: '#4d6350', hasGrain: false },
  { id: 'egger-u599', name: 'Egger U599 ST9 Индиго синий', brand: 'Egger', code: 'U599', kind: 'chipboard', color: '#3a5578', hasGrain: false },
  { id: 'egger-u545', name: 'Egger U545 ST9 Синий балтийский', brand: 'Egger', code: 'U545', kind: 'chipboard', color: '#3a5578', hasGrain: false },
  { id: 'egger-u540', name: 'Egger U540 ST9 Деним голубой', brand: 'Egger', code: 'U540', kind: 'chipboard', color: '#3a5578', hasGrain: false },
  { id: 'egger-u525', name: 'Egger U525 ST9 Делфт голубой', brand: 'Egger', code: 'U525', kind: 'chipboard', color: '#3a5578', hasGrain: false },
  { id: 'egger-u504', name: 'Egger U504 ST9 Альпийское озеро', brand: 'Egger', code: 'U504', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'egger-u502', name: 'Egger U502 ST9 Синий дымчатый', brand: 'Egger', code: 'U502', kind: 'chipboard', color: '#3a5578', hasGrain: false },
  { id: 'egger-u420', name: 'Egger U420 ST9 Лиловый', brand: 'Egger', code: 'U420', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'egger-u399', name: 'Egger U399 ST9 Красный гранат', brand: 'Egger', code: 'U399', kind: 'chipboard', color: '#8d3a32', hasGrain: false },
  { id: 'egger-u335', name: 'Egger U335 ST9 Красно-коричневый', brand: 'Egger', code: 'U335', kind: 'chipboard', color: '#8d3a32', hasGrain: false },
  { id: 'egger-u325', name: 'Egger U325 ST9 Розовый антик', brand: 'Egger', code: 'U325', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'egger-u321', name: 'Egger U321 ST9 Красный китайский', brand: 'Egger', code: 'U321', kind: 'chipboard', color: '#8d3a32', hasGrain: false },
  { id: 'egger-u311', name: 'Egger U311 ST9 Бургундский красный', brand: 'Egger', code: 'U311', kind: 'chipboard', color: '#8d3a32', hasGrain: false },
  { id: 'egger-u222', name: 'Egger U222 ST9 Крем бежевый', brand: 'Egger', code: 'U222', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: 'egger-u216', name: 'Egger U216 ST9 Камель бежевый', brand: 'Egger', code: 'U216', kind: 'chipboard', color: '#c8a578', hasGrain: true },
  { id: 'egger-u211', name: 'Egger U211 ST9 Миндаль бежевый', brand: 'Egger', code: 'U211', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: 'egger-u201', name: 'Egger U201 ST9 Серая галька', brand: 'Egger', code: 'U201', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-u163', name: 'Egger U163 ST9 Карри жёлтый', brand: 'Egger', code: 'U163', kind: 'chipboard', color: '#c9a227', hasGrain: false },
  { id: 'egger-u156', name: 'Egger U156 ST9 Бежевый песок', brand: 'Egger', code: 'U156', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: 'egger-u125', name: 'Egger U125 ST9 Жёлтый песок', brand: 'Egger', code: 'U125', kind: 'chipboard', color: '#c9a227', hasGrain: false },
  { id: 'egger-u115', name: 'Egger U115 ST9 Карат бежевый', brand: 'Egger', code: 'U115', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: 'egger-u113', name: 'Egger U113 ST9 Коттон бежевый', brand: 'Egger', code: 'U113', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: 'egger-u104', name: 'Egger U104 ST9 Алебастр белый', brand: 'Egger', code: 'U104', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'egger-h3860', name: 'Egger H3860 ST9 Клён сахарный шампань', brand: 'Egger', code: 'H3860', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'egger-h3840', name: 'Egger H3840 ST9 Клён Мандал натуральный', brand: 'Egger', code: 'H3840', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'egger-h3734', name: 'Egger H3734 ST9 Орех Дижон натуральный', brand: 'Egger', code: 'H3734', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: 'egger-h3730', name: 'Egger H3730 ST10 Гикори натуральный', brand: 'Egger', code: 'H3730', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'egger-h3710', name: 'Egger H3710 ST12 Орех Карини натуральный', brand: 'Egger', code: 'H3710', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: 'egger-h3702', name: 'Egger H3702 ST10 Орех Пацифик табак', brand: 'Egger', code: 'H3702', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: 'egger-h3700', name: 'Egger H3700 ST10 Орех Пацифик натуральный', brand: 'Egger', code: 'H3700', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: 'egger-h3450', name: 'Egger H3450 ST22 Флитвуд белый', brand: 'Egger', code: 'H3450', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'egger-h3433', name: 'Egger H3433 ST22 Сосна Аланд полярная', brand: 'Egger', code: 'H3433', kind: 'chipboard', color: '#c8a578', hasGrain: true },
  { id: 'egger-h3430', name: 'Egger H3430 ST22 Сосна Аланд белая', brand: 'Egger', code: 'H3430', kind: 'chipboard', color: '#f2f0ec', hasGrain: true },
  { id: 'egger-h3398', name: 'Egger H3398 ST12 Дуб Кендал коньяк', brand: 'Egger', code: 'H3398', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h3395', name: 'Egger H3395 ST12 Дуб Корбридж натуральный', brand: 'Egger', code: 'H3395', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h3368', name: 'Egger H3368 ST9 Дуб Ланкастер натуральный', brand: 'Egger', code: 'H3368', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h3359', name: 'Egger H3359 ST32 Дуб Давенпорт натуральный светлый', brand: 'Egger', code: 'H3359', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h3331', name: 'Egger H3331 ST10 Дуб Небраска натуральный', brand: 'Egger', code: 'H3331', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h3325', name: 'Egger H3325 ST28 Дуб Гладстоун табак', brand: 'Egger', code: 'H3325', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h3317', name: 'Egger H3317 ST28 Дуб Кунео коричневый', brand: 'Egger', code: 'H3317', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h3309', name: 'Egger H3309 ST28 Дуб Гладстоун песочный', brand: 'Egger', code: 'H3309', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h3303', name: 'Egger H3303 ST10 Дуб Гамильтон натуральный', brand: 'Egger', code: 'H3303', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h3198', name: 'Egger H3198 ST19 Файнлайн тёмно-серый', brand: 'Egger', code: 'H3198', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-h3197', name: 'Egger H3197 ST19 Файнлайн средне-серый', brand: 'Egger', code: 'H3197', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-h3195', name: 'Egger H3195 ST19 Файнлайн белый', brand: 'Egger', code: 'H3195', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'egger-h3190', name: 'Egger H3190 ST19 Металлик Файнлайн антрацит', brand: 'Egger', code: 'H3190', kind: 'chipboard', color: '#2b2d30', hasGrain: false },
  { id: 'egger-h3176', name: 'Egger H3176 ST37 Дуб Галифакс олово', brand: 'Egger', code: 'H3176', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h3170', name: 'Egger H3170 ST12 Дуб Кендал натуральный', brand: 'Egger', code: 'H3170', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h3157', name: 'Egger H3157 ST12 Дуб Винченца', brand: 'Egger', code: 'H3157', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h3156', name: 'Egger H3156 ST12 Дуб Корбридж серый', brand: 'Egger', code: 'H3156', kind: 'chipboard', color: '#9a9a97', hasGrain: true },
  { id: 'egger-h3154', name: 'Egger H3154 ST36 Дуб Чарльстон тёмно-коричневый', brand: 'Egger', code: 'H3154', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h3152', name: 'Egger H3152 ST19 Дуб Виченца белёный', brand: 'Egger', code: 'H3152', kind: 'chipboard', color: '#f2f0ec', hasGrain: true },
  { id: 'egger-h3146', name: 'Egger H3146 ST19 Дуб Лоренцо бежево-серый', brand: 'Egger', code: 'H3146', kind: 'chipboard', color: '#9a9a97', hasGrain: true },
  { id: 'egger-h3133', name: 'Egger H3133 ST12 Дуб Давос трюфель', brand: 'Egger', code: 'H3133', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h3131', name: 'Egger H3131 ST12 Дуб Давос натуральный', brand: 'Egger', code: 'H3131', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h309', name: 'Egger H309 ST12 Дуб Тонсберг коричневый', brand: 'Egger', code: 'H309', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h305', name: 'Egger H305 ST12 Дуб Тонсберг натуральный', brand: 'Egger', code: 'H305', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h3043', name: 'Egger H3043 ST12 Эвкалипт тёмно-коричневый', brand: 'Egger', code: 'H3043', kind: 'chipboard', color: '#6b4c3a', hasGrain: false },
  { id: 'egger-h3012', name: 'Egger H3012 ST22 Кокоболо натуральный', brand: 'Egger', code: 'H3012', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'egger-h3003', name: 'Egger H3003 ST19 Дуб Норидж', brand: 'Egger', code: 'H3003', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h2033', name: 'Egger H2033 ST10 Дуб Хантон тёмный', brand: 'Egger', code: 'H2033', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h1910', name: 'Egger H1910 ST9 Бук луговой', brand: 'Egger', code: 'H1910', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'egger-h1732', name: 'Egger H1732 ST9 Берёза песочная', brand: 'Egger', code: 'H1732', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'egger-h1715', name: 'Egger H1715 ST12 Орех Парона', brand: 'Egger', code: 'H1715', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: 'egger-h1714', name: 'Egger H1714 ST19 Орех Линкольн', brand: 'Egger', code: 'H1714', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: 'egger-h1710', name: 'Egger H1710 ST10 Каштан Кентукки песочный', brand: 'Egger', code: 'H1710', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: 'egger-h1636', name: 'Egger H1636 ST12 Вишня Локарно', brand: 'Egger', code: 'H1636', kind: 'chipboard', color: '#8d3a32', hasGrain: true },
  { id: 'egger-h1487', name: 'Egger H1487 ST22 Пихта Брамберг', brand: 'Egger', code: 'H1487', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'egger-h1401', name: 'Egger H1401 ST22 Сосна Касцина', brand: 'Egger', code: 'H1401', kind: 'chipboard', color: '#c8a578', hasGrain: true },
  { id: 'egger-h1399', name: 'Egger H1399 ST10 Дуб Денвер трюфель', brand: 'Egger', code: 'H1399', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h1386', name: 'Egger H1386 ST40 Дуб Каселла коричневый', brand: 'Egger', code: 'H1386', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h1385', name: 'Egger H1385 ST40 Дуб Каселла натуральный', brand: 'Egger', code: 'H1385', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h1367', name: 'Egger H1367 ST40 Дуб Каселла натуральный светлый', brand: 'Egger', code: 'H1367', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h1362', name: 'Egger H1362 ST12 Дуб Барония светлый', brand: 'Egger', code: 'H1362', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h1346', name: 'Egger H1346 ST32 Дуб Шерман антрацит', brand: 'Egger', code: 'H1346', kind: 'chipboard', color: '#2b2d30', hasGrain: true },
  { id: 'egger-h1344', name: 'Egger H1344 ST32 Дуб Шерман коньяк коричневый', brand: 'Egger', code: 'H1344', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h1330', name: 'Egger H1330 ST10 Дуб Санта-Фе винтаж', brand: 'Egger', code: 'H1330', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h1318', name: 'Egger H1318 ST10 Дикий дуб натуральный', brand: 'Egger', code: 'H1318', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h1313', name: 'Egger H1313 ST10 Дуб Уайт-Ривер серо-коричневый', brand: 'Egger', code: 'H1313', kind: 'chipboard', color: '#9a9a97', hasGrain: true },
  { id: 'egger-h1312', name: 'Egger H1312 ST10 Дуб Уайт-Ривер песочно-бежевый', brand: 'Egger', code: 'H1312', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h1307', name: 'Egger H1307 ST19 Орех Вармия коричневый', brand: 'Egger', code: 'H1307', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: 'egger-h1303', name: 'Egger H1303 ST12 Дуб Бельмонт коричневый', brand: 'Egger', code: 'H1303', kind: 'chipboard', color: '#f2f0ec', hasGrain: true },
  { id: 'egger-h1277', name: 'Egger H1277 ST9 Акация Лэйклэнд светлая', brand: 'Egger', code: 'H1277', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'egger-h1250', name: 'Egger H1250 ST36 Ясень Наварра', brand: 'Egger', code: 'H1250', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'egger-h1242', name: 'Egger H1242 ST10 Акация Шеффилд натуральный', brand: 'Egger', code: 'H1242', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'egger-h1225', name: 'Egger H1225 ST12 Ясень Тронхейм', brand: 'Egger', code: 'H1225', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'egger-h1223', name: 'Egger H1223 ST19 Ясень Севилья', brand: 'Egger', code: 'H1223', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'egger-h1199', name: 'Egger H1199 ST12 Дуб термо чёрно-коричневый', brand: 'Egger', code: 'H1199', kind: 'chipboard', color: '#2b2d30', hasGrain: true },
  { id: 'egger-h1181', name: 'Egger H1181 ST37 Дуб Галифакс табак', brand: 'Egger', code: 'H1181', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h1180', name: 'Egger H1180 ST37 Дуб Галифакс натуральный', brand: 'Egger', code: 'H1180', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h1176', name: 'Egger H1176 ST37 Дуб Галифакс белый', brand: 'Egger', code: 'H1176', kind: 'chipboard', color: '#f2f0ec', hasGrain: true },
  { id: 'egger-h1145', name: 'Egger H1145 ST10 Дуб Бардолино натуральный', brand: 'Egger', code: 'H1145', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h1142', name: 'Egger H1142 ST36 Дуб Сакраменто коричневый', brand: 'Egger', code: 'H1142', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-h1113', name: 'Egger H1113 ST10 Дуб Канзас коричневый', brand: 'Egger', code: 'H1113', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: 'egger-f765', name: 'Egger F765 ST20 Серебристый матовый', brand: 'Egger', code: 'F765', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-f685', name: 'Egger F685 ST10 Акапулько', brand: 'Egger', code: 'F685', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'egger-f637', name: 'Egger F637 ST10 Хромикс белый', brand: 'Egger', code: 'F637', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: 'egger-f528', name: 'Egger F528 ST20 Металл брашированный бронзовый', brand: 'Egger', code: 'F528', kind: 'chipboard', color: '#a2a3a1', hasGrain: false },
  { id: 'egger-f433', name: 'Egger F433 ST10 Лён антрацит', brand: 'Egger', code: 'F433', kind: 'chipboard', color: '#2b2d30', hasGrain: false },
  { id: 'egger-f416', name: 'Egger F416 ST10 Текстиль бежевый', brand: 'Egger', code: 'F416', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: 'egger-f323', name: 'Egger F323 ST20 Кобра бронза', brand: 'Egger', code: 'F323', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'egger-f302', name: 'Egger F302 ST87 Ферро бронза', brand: 'Egger', code: 'F302', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'egger-f243', name: 'Egger F243 ST10 Мрамор Кандела светло-серый', brand: 'Egger', code: 'F243', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: 'egger-f235', name: 'Egger F235 ST10 Сланец Скиваро', brand: 'Egger', code: 'F235', kind: 'chipboard', color: '#cdc9c2', hasGrain: false },
  { id: 'egger-f206', name: 'Egger F206 ST9 Камень Пьетра Гриджиа чёрный', brand: 'Egger', code: 'F206', kind: 'chipboard', color: '#2b2d30', hasGrain: false },
  { id: 'egger-f187', name: 'Egger F187 ST9 Бетон Чикаго тёмно-серый', brand: 'Egger', code: 'F187', kind: 'chipboard', color: '#a2a3a1', hasGrain: false },
  { id: 'egger-f186', name: 'Egger F186 ST9 Бетон Чикаго светло-серый', brand: 'Egger', code: 'F186', kind: 'chipboard', color: '#a2a3a1', hasGrain: false },
  { id: '', name: 'Томский Шалфей', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-2', name: 'Томский Чёрный', brand: 'Томский', code: '', kind: 'chipboard', color: '#2b2d30', hasGrain: false },
  { id: '-3', name: 'Томский Форест', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-4', name: 'Томский Фон Мускат', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-5', name: 'Томский Фон Бежевый', brand: 'Томский', code: '', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: '-6', name: 'Томский Фон Атлантик', brand: 'Томский', code: '', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: '-7', name: 'Томский Тэфи', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-8', name: 'Томский Титан', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-9', name: 'Томский Терракота', brand: 'Томский', code: '', kind: 'chipboard', color: '#8d3a32', hasGrain: false },
  { id: '-10', name: 'Томский Супербелый', brand: 'Томский', code: '', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: '-11', name: 'Томский Синий', brand: 'Томский', code: '', kind: 'chipboard', color: '#3a5578', hasGrain: false },
  { id: '-12', name: 'Томский Серый', brand: 'Томский', code: '', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: '-13', name: 'Томский Светло-Жёлтый', brand: 'Томский', code: '', kind: 'chipboard', color: '#c9a227', hasGrain: false },
  { id: '-14', name: 'Томский Салатовый', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-15', name: 'Томский Розовый кварц', brand: 'Томский', code: '', kind: 'chipboard', color: '#c9a5a0', hasGrain: false },
  { id: '-16', name: 'Томский Розовый', brand: 'Томский', code: '', kind: 'chipboard', color: '#c9a5a0', hasGrain: false },
  { id: '-17', name: 'Томский Оранж', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-18', name: 'Томский Лаванда', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-19', name: 'Томский Крем', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-20', name: 'Томский Красный', brand: 'Томский', code: '', kind: 'chipboard', color: '#8d3a32', hasGrain: false },
  { id: '-21', name: 'Томский Капучино', brand: 'Томский', code: '', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: '-22', name: 'Томский Индиго', brand: 'Томский', code: '', kind: 'chipboard', color: '#3a5578', hasGrain: false },
  { id: '-23', name: 'Томский Жёлтый', brand: 'Томский', code: '', kind: 'chipboard', color: '#c9a227', hasGrain: false },
  { id: '-24', name: 'Томский Голубой', brand: 'Томский', code: '', kind: 'chipboard', color: '#3a5578', hasGrain: false },
  { id: '-25', name: 'Томский Белый', brand: 'Томский', code: '', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: '-26', name: 'Томский Базальт', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-27', name: 'Томский Алюминий', brand: 'Томский', code: '', kind: 'chipboard', color: '#a2a3a1', hasGrain: false },
  { id: '-28', name: 'Томский Цемент Тёмный', brand: 'Томский', code: '', kind: 'chipboard', color: '#a2a3a1', hasGrain: false },
  { id: '-29', name: 'Томский Цемент', brand: 'Томский', code: '', kind: 'chipboard', color: '#a2a3a1', hasGrain: false },
  { id: '-30', name: 'Томский Файерстоун', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-31', name: 'Томский Финдус', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-32', name: 'Томский Тегола', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-33', name: 'Томский Сириус', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-34', name: 'Томский Планка', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-35', name: 'Томский Лофт', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-36', name: 'Томский Кена', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-37', name: 'Томский Камень', brand: 'Томский', code: '', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: '-38', name: 'Томский Ена', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-39', name: 'Томский Бетон Пайн', brand: 'Томский', code: '', kind: 'chipboard', color: '#a2a3a1', hasGrain: false },
  { id: '-40', name: 'Томский Ясень Шимо Тёмный', brand: 'Томский', code: '', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: '-41', name: 'Томский Ясень Шимо Светлый', brand: 'Томский', code: '', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: '-42', name: 'Томский Ясень Рибера', brand: 'Томский', code: '', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: '-43', name: 'Томский Ясень Борнхольм', brand: 'Томский', code: '', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: '-44', name: 'Томский Ясень Анкор Тёмный', brand: 'Томский', code: '', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: '-45', name: 'Томский Ясень Анкор Светлый', brand: 'Томский', code: '', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: '-46', name: 'Томский Ясень Анкор Белый', brand: 'Томский', code: '', kind: 'chipboard', color: '#f2f0ec', hasGrain: true },
  { id: '-47', name: 'Томский Туя', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-48', name: 'Томский Сосна Выбеленная', brand: 'Томский', code: '', kind: 'chipboard', color: '#f2f0ec', hasGrain: true },
  { id: '-49', name: 'Томский Сосна Винтерберг', brand: 'Томский', code: '', kind: 'chipboard', color: '#c8a578', hasGrain: true },
  { id: '-50', name: 'Томский Сосна Астрид', brand: 'Томский', code: '', kind: 'chipboard', color: '#c8a578', hasGrain: true },
  { id: '-51', name: 'Томский Слива Валлис', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-52', name: 'Томский Пикард', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-53', name: 'Томский Орех Таволато', brand: 'Томский', code: '', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: '-54', name: 'Томский Орех Палдао', brand: 'Томский', code: '', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: '-55', name: 'Томский Орех Итальянский', brand: 'Томский', code: '', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: '-56', name: 'Томский Орех Донской', brand: 'Томский', code: '', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: '-57', name: 'Томский Ольха Светлая', brand: 'Томский', code: '', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: '-58', name: 'Томский Ольха', brand: 'Томский', code: '', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: '-59', name: 'Томский Олеандр Бежевый', brand: 'Томский', code: '', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: '-60', name: 'Томский Олеандр', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-61', name: 'Томский Ноче Экко', brand: 'Томский', code: '', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: '-62', name: 'Томский Ноче Пегассо', brand: 'Томский', code: '', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: '-63', name: 'Томский Ноче Гварнери', brand: 'Томский', code: '', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: '-64', name: 'Томский Моринга', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-65', name: 'Томский Локи', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-66', name: 'Томский Клён Танзай', brand: 'Томский', code: '', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: '-67', name: 'Томский Канадский Дуб', brand: 'Томский', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-68', name: 'Томский Дуб Юстус', brand: 'Томский', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-69', name: 'Томский Дуб Термо Тёмный', brand: 'Томский', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-70', name: 'Томский Дуб Сонома', brand: 'Томский', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-71', name: 'Томский Дуб Седан', brand: 'Томский', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-72', name: 'Томский Дуб Самдал', brand: 'Томский', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-73', name: 'Томский Дуб Поненте', brand: 'Томский', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-74', name: 'Томский Дуб Паллада', brand: 'Томский', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-75', name: 'Томский Дуб Кронберг', brand: 'Томский', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-76', name: 'Томский Дуб Кобург', brand: 'Томский', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-77', name: 'Томский Дуб Интра', brand: 'Томский', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-78', name: 'Томский Дуб Джаггер Светлый', brand: 'Томский', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-79', name: 'Томский Дуб Выбеленный', brand: 'Томский', code: '', kind: 'chipboard', color: '#f2f0ec', hasGrain: true },
  { id: '-80', name: 'Томский Дуб Вотан', brand: 'Томский', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-81', name: 'Томский Дуб Бунратти', brand: 'Томский', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-82', name: 'Томский Дуб Атланта', brand: 'Томский', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-83', name: 'Томский Дуб Аризона', brand: 'Томский', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-84', name: 'Томский Вишня Хансен', brand: 'Томский', code: '', kind: 'chipboard', color: '#8d3a32', hasGrain: true },
  { id: '-85', name: 'Томский Вишня Оксфорд', brand: 'Томский', code: '', kind: 'chipboard', color: '#8d3a32', hasGrain: true },
  { id: '-86', name: 'Томский Венге Цаво', brand: 'Томский', code: '', kind: 'chipboard', color: '#3b2f2a', hasGrain: true },
  { id: '-87', name: 'Томский Венге Светлый', brand: 'Томский', code: '', kind: 'chipboard', color: '#3b2f2a', hasGrain: true },
  { id: '-88', name: 'Томский Венге Линум', brand: 'Томский', code: '', kind: 'chipboard', color: '#3b2f2a', hasGrain: true },
  { id: '-89', name: 'Томский Венге', brand: 'Томский', code: '', kind: 'chipboard', color: '#3b2f2a', hasGrain: true },
  { id: '2', name: 'Томский Бук Бавария (2)', brand: 'Томский', code: '', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: '-90', name: 'Томский Бук Бавария', brand: 'Томский', code: '', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: '-91', name: 'Томский Бодега Светлая', brand: 'Томский', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-92', name: 'Томский Бодега Белая', brand: 'Томский', code: '', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
  { id: '-93', name: 'Томский Акация Светлая', brand: 'Томский', code: '', kind: 'chipboard', color: '#c2a07a', hasGrain: true },
  { id: 'byspan', name: 'ЛДСП Byspan', brand: '', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'smart', name: 'ЛДСП SMart', brand: '', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'cleaf', name: 'ЛДСП Cleaf', brand: '', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'kronospan', name: 'ЛДСП Kronospan', brand: '', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: 'egger', name: 'ЛДСП Egger', brand: '', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-94', name: 'ЛДСП Томский', brand: '', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-95', name: 'ЛДСП светло серый', brand: '', code: '', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: '-96', name: 'ЛДСП Дуб каселла', brand: '', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-97', name: 'Орех', brand: '', code: '', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: '18', name: 'МДФ краска 18', brand: '', code: '', kind: 'mdf', color: '#b8b4ac', hasGrain: false },
  { id: '-98', name: 'тас', brand: '', code: '', kind: 'other', color: '#b8b4ac', hasGrain: false },
  { id: '-99', name: 'тас', brand: '', code: '', kind: 'other', color: '#b8b4ac', hasGrain: false },
  { id: '16', name: 'МДФ краска 16', brand: '', code: '', kind: 'mdf', color: '#b8b4ac', hasGrain: false },
  { id: '-100', name: 'ДСП столещница', brand: '', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '32', name: 'МДФ склейка 32', brand: '', code: '', kind: 'mdf', color: '#b8b4ac', hasGrain: false },
  { id: '6', name: 'ХДФ 6', brand: '', code: '', kind: 'hardboard', color: '#b8b4ac', hasGrain: false },
  { id: '22', name: 'МДФ пленка 22', brand: '', code: '', kind: 'mdf', color: '#b8b4ac', hasGrain: false },
  { id: '18-2', name: 'МДФ пленка 18', brand: '', code: '', kind: 'mdf', color: '#b8b4ac', hasGrain: false },
  { id: '16-2', name: 'МДФ пленка 16', brand: '', code: '', kind: 'mdf', color: '#b8b4ac', hasGrain: false },
  { id: '-101', name: 'ХДФ', brand: '', code: '', kind: 'hardboard', color: '#b8b4ac', hasGrain: false },
  { id: '-102', name: 'Терракота', brand: '', code: '', kind: 'chipboard', color: '#8d3a32', hasGrain: false },
  { id: '-103', name: 'Фон черный', brand: '', code: '', kind: 'chipboard', color: '#2b2d30', hasGrain: false },
  { id: '-104', name: 'Серый', brand: '', code: '', kind: 'chipboard', color: '#9a9a97', hasGrain: false },
  { id: '-105', name: 'Орех палдао', brand: '', code: '', kind: 'chipboard', color: '#6f4b32', hasGrain: true },
  { id: '-106', name: 'ЛДСП Тэфи', brand: '', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-107', name: 'Крем', brand: '', code: '', kind: 'chipboard', color: '#b8b4ac', hasGrain: false },
  { id: '-108', name: 'Капучино', brand: '', code: '', kind: 'chipboard', color: '#d9cbb3', hasGrain: false },
  { id: '-109', name: 'Дуб сонома', brand: '', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-110', name: 'Дуб аризона', brand: '', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-111', name: 'Дуб бунратти', brand: '', code: '', kind: 'chipboard', color: '#b98d57', hasGrain: true },
  { id: '-112', name: 'Белый', brand: '', code: '', kind: 'chipboard', color: '#f2f0ec', hasGrain: false },
]

/** Кітапханадағы брендтер — сүзгі үшін, кездесу ретімен. */
export const DECOR_BRANDS: string[] = [
  ...new Set(DECOR_LIBRARY.map((d) => d.brand).filter((b) => b !== '')),
]

/**
 * Іздеу: атауы, артикулы және бренді бойынша.
 *
 * Сұраныс БІРНЕШЕ сөзден тұруы мүмкін («egger дуб»), сондықтан сөздер бөлек
 * тексеріледі — цех жадындағы екі белгіні қатар жазады.
 */
export function searchDecors(query: string, brand?: string, limit = 60): DecorEntry[] {
  const words = query.toLowerCase().split(/\s+/).filter(Boolean)
  const out: DecorEntry[] = []
  for (const d of DECOR_LIBRARY) {
    if (brand && d.brand !== brand) continue
    const hay = `${d.name} ${d.code} ${d.brand}`.toLowerCase()
    if (words.every((w) => hay.includes(w))) out.push(d)
    if (out.length >= limit) break
  }
  return out
}

export function findDecor(id: string): DecorEntry | undefined {
  return DECOR_LIBRARY.find((d) => d.id === id)
}
